about:
  home: http://github.com/bioidiap/bob.learn.activation
  license: BSD License
  summary: Bindings for bob.machine's Activation functors
build:
  preserve_egg_dir: true
package:
  name: bob.learn.activation
  version: 2.0.4
requirements:
  build:
  - python
  - setuptools
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
  - cmake
  run:
  - python
  - setuptools
  - bob.extension >2.0.4
  - bob.blitz
  - bob.core
  - bob.io.base
source:
  fn: bob.learn.activation-2.0.4.zip
  md5: 28425bc09c9a917da8f58192ea9a0f4a
  url: https://pypi.python.org/packages/source/b/bob.learn.activation/bob.learn.activation-2.0.4.zip
test:
  commands:
  - nosetests -sv bob.learn.activation
  imports:
  - bob
  - bob.learn
  - bob.learn.activation
  requires:
  - nose
