package:
  name: bob.math
  version: "2.0.3"

source:
  fn: bob.math-2.0.3.zip
  url: https://pypi.python.org/packages/source/b/bob.math/bob.math-2.0.3.zip
  md5: 0f010af6ce20fe6614570edff94e593f

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - bob.core
    - boost
    - cmake

  run:
    - python
    - setuptools
    - bob.core
    - boost

test:
  requires:
    - nose

  imports:
    - bob
    - bob.math

  commands:
    - nosetests -sv bob.math

about:
  home: http://github.com/bioidiap/bob.math
  license: BSD License
  summary: 'LAPACK and BLAS interfaces for Bob'
