about:
  home: http://github.com/bioidiap/bob.ip.draw
  license: BSD License
  summary: Line and Box drawing utilities of Bob
build:
  preserve_egg_dir: true
package:
  name: bob.ip.draw
  version: 2.0.3
requirements:
  build:
  - python
  - setuptools
  - bob.extension >2.0.4
  - bob.blitz
  - gcc
  run:
  - python
  - setuptools
  - bob.extension >2.0.4
  - bob.blitz
source:
  fn: bob.ip.draw-2.0.3.zip
  md5: 11616e069e34552e5889e5ae783aa636
  url: https://pypi.python.org/packages/source/b/bob.ip.draw/bob.ip.draw-2.0.3.zip
test:
  commands:
  - nosetests -sv bob.ip.draw
  imports:
  - bob
  - bob.ip
  - bob.ip.draw
  requires:
  - nose
