about:
  home: http://github.com/bioidiap/bob.learn.em
  license: BSD License
  summary: Bindings for emelaneous machines and trainers of Bob
build:
  preserve_egg_dir: true
package:
  name: bob.learn.em
  version: 2.0.7
requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core >2.0.5
  - bob.io.base
  - bob.sp
  - bob.math
  - bob.learn.activation
  - bob.learn.linear
  - cmake
  run:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core >2.0.5
  - bob.io.base
  - bob.sp
  - bob.math
  - bob.learn.activation
  - bob.learn.linear
source:
  fn: bob.learn.em-2.0.7.zip
  md5: 2be38e9a6be30553ef0f2ae4f69122f4
  url: https://pypi.python.org/packages/source/b/bob.learn.em/bob.learn.em-2.0.7.zip
test:
  commands:
  - nosetests -sv bob.learn.em
  imports:
  - bob
  - bob.learn
  - bob.learn.em
  - bob.learn.em.test
  requires:
  - nose
