package:
  name: bob.extension
  version: "2.0.11"

source:
  fn: bob.extension-2.0.11.zip
  url: https://pypi.python.org/packages/source/b/bob.extension/bob.extension-2.0.11.zip
  #md5: a2ccb5f5a5f0abee02488565e636441d

build:
  preserve_egg_dir: True
  entry_points:
    - bob_new_version.py = bob.extension.scripts:new_version
    - bob_dependecy_graph.py = bob.extension.scripts:dependency_graph

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  requires:
    - nose
    - boost
    - cmake
    - pkg-config
    - libblitz
    - nomkl
    - numpy
    - gcc

  imports:
    - bob
    - bob.extension
    - bob.extension.scripts

  commands:
    - bob_new_version.py --help
    - bob_dependecy_graph.py --help
    - nosetests -sv bob.extension --exclude=test_cflags_other --exclude=test_extensions

about:
  home: http://github.com/bioidiap/bob.extension
  license: BSD License
  summary: 'Building of Python/C++ extensions for Bob'
