package:
  name: bob.sp
  version: "2.0.4"

source:
  fn: bob.sp-2.0.4.zip
  url: https://pypi.python.org/packages/source/b/bob.sp/bob.sp-2.0.4.zip
  md5: 9260da350dfb351c54e3d7e281d229a3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bob.sp = bob.sp:main
    #
    # Would create an entry point called bob.sp that calls bob.sp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - cmake

  run:
    - python
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core

test:
  # Python imports
  imports:
    - bob
    - bob.sp

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - nosetests -sv bob.sp


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://github.com/bioidiap/bob.sp
  license: BSD License
  summary: "Bob's signal processing utilities"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
