about:
  home: https://github.com/bioidiap/bob.ip.optflow.liu
  license: GNU General Public License v3 (GPLv3)
  summary: Python bindings to the optical flow framework by C. Liu
build:
  entry_points:
  - bob_of_liu.py = bob.ip.optflow.liu.script.flow:main
  preserve_egg_dir: true
package:
  name: bob.ip.optflow.liu
  version: 2.0.5
requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.io.base
  - bob.io.image
  - bob.io.video
  - bob.ip.color
  run:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.io.base
  - bob.io.image
  - bob.io.video
  - bob.ip.color
source:
  fn: bob.ip.optflow.liu-2.0.5.zip
  md5: 4fe7ce56f749b7a19e683cb16a946b94
  url: https://pypi.python.org/packages/source/b/bob.ip.optflow.liu/bob.ip.optflow.liu-2.0.5.zip
test:
  commands:
  - bob_of_liu.py --help
  - nosetests -sv bob.ip.optflow.liu
  imports:
  - bob
  - bob.ip
  - bob.ip.optflow
  - bob.ip.optflow.liu
  - bob.ip.optflow.liu.script
  requires:
  - nose
