package:
  name: bob.io.base
  version: "2.0.8"

source:
  fn: bob.io.base-2.0.8.zip
  url: https://pypi.python.org/packages/source/b/bob.io.base/bob.io.base-2.0.8.zip
  md5: f81e1e04466048cb022f4fa363bf6fe0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bob.io.base = bob.io.base:main
    #
    # Would create an entry point called bob.io.base that calls bob.io.base.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - hdf5
    - cmake

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - hdf5

test:
  # Python imports
  imports:
    - bob
    - bob.io
    - bob.io.base

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - nosetests -sv bob.io.base

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://github.com/bioidiap/bob.io.base
  license: BSD License
  summary: 'Basic IO for Bob'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
